server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    host: 192.168.1.112
    username: iam
    password: iam59!z$
    database: iam
    max_idle_connections: 10
    max_open_connections: 10
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
